apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 30; done;']
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spark  
            topologyKey: "kubernetes.io/hostname"  
      containers:
      - name: spark
        image: kaoutarc/spark:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 8090
        - containerPort: 15002  

---
apiVersion: v1
kind: Service
metadata:
  name: spark
spec:
  selector:
    app: spark
  ports:
  - name: master-port
    port: 7077       
    targetPort: 7077 
  - name: spark-ui-port
    port: 4040       
    targetPort: 4040 
  - name: spark-ui-port-sec
    port: 4041       
    targetPort: 4041 
  - name: webui-port
    port: 8090       
    targetPort: 8090 
  - name: connect-server-port
    port: 15002      
    targetPort: 15002 